#!/bin/sh

# Placement daemon script that verifies service status, used for healthcheck and deploy. #placement#deploy#idoc

fail() { echo "BAD $@"; exit 0; }
ok() { echo "OK $@"; exit 0; }

# EDITME

response=$(curl -Lsf http://localhost:8000/healthcheck/ -w '%{http_code}' -o /dev/null) || fail "unable to curl"

if [ "$response" = "200" ]; then
    ok "$response"
else
    fail "$response"
fi