#!/bin/sh -ex

# Jenkins script that writes the release into placement. #build#placement#deploy#idoc

set -e

. $(dirname $0)/common

RELEASE_ID=$1; shift

ZK_HOSTS=${ZK_HOSTS:-"localhost:2180,localhost:2179,localhost:2178"}

VENV_DIR=$($mktemp -d ./virtualenv.XXXX)
virtualenv ${VENV_DIR}
. ${VENV_DIR}/bin/activate
curl -ssL http://href.prezi.com/snakebasket | sh
sb install -e git+git@github.com:prezi/placement-client.git@master#egg=prezi-placement-client

${VENV_DIR}/src/prezi-placement-client/placement.py\
  -n fake-node --hosts ${ZK_HOSTS} \
  $PROJECT_NAME write_release $RELEASE_ID prezireleases/${PROJECT_NAME}/${PROJECT_NAME}-${RELEASE_ID}.tar.bz2

deactivate
rm -rf ${VENV_DIR}